version: '2.1'

services:
  mlflow-src:
    container_name: app
    image: bitnami/mlflow:latest
    volumes:
      - /src:/app
    networks:
      - mlflow-net
    depends_on:
      - mlflow-database

  mlflow-database:
    container_name: mlflow-database
    image: bitnami/postgresql:latest
    volumes:
      - /postgres-data:/bitnami/postgresql
    networks:
      - mlflow-net
    ports:
      - "5432:5432"
    env_file:
      - .envs/.postgres

  mlflow-server:
    container_name: mlflow-server
    build:
      context: .
      dockerfile: docker/Dockerfile.server
    networks:
      - mlflow-net
    ports:
      - "5000:5000"
    depends_on:
      - mlflow-database
    env_file:
      - .envs/.postgres
      - .envs/.mlflow

networks:
  mlflow-net:
