FROM bitnami/mlflow:latest

# Set the entrypoint to bash
ENTRYPOINT [ "/bin/bash", "-c" ]

# Set the default command for the container
CMD ["mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@mlflow-database:5432/${POSTGRES_DB} --default-artifact-root ${MLFLOW_DEFAULT_ARTIFACT_ROOT}"]
